export const userMocks = {
  getUsers: {
    result: [
      {
        id: 1,
        username: 'user1',
        display_name: 'Вася Пупкин',
        avatar: 'http://127.0.0.1:8000/media/avatars/user_1/avatar.jpg',
        recipes_count: 1,
        is_follow: true,
        is_follower: false,
      },
      {
        id: 2,
        username: 'user2',
        display_name: 'Пупкин',
        avatar: 'http://127.0.0.1:8000/media/avatars/user_2/avatar.jpg',
        recipes_count: 2,
        is_follow: true,
        is_follower: false,
      },
    ],
  },
  getUserData: {
    username: 'test',
    result: {
      id: 1,
      username: 'user1',
      display_name: 'Светлана',
      email: 'vasya_pupkin@example.com',
      avatar: 'path/to/avatar.jpg',
      city: 'Москва',
      country: 'Россия',
      bio: 'Описание пользователя',
      date_joined: '2022-01-01',
      first_name: 'Василий',
      last_name: 'Иванов',
      is_active: true,
      is_banned: false,
      is_staff: false,
      is_admin: false,
    },
  },
  patchUserData: {
    username: 'test',
    reqquestBody: {
      display_name: 'string',
      phone: '+79261112233',
      date_joined: '2024-03-05T14:23:27.430Z',
      country: 'string',
      city: 'string',
      first_name: 'string',
      last_name: 'string',
      bio: 'string',
    },
    result: {
      id: 66,
      username: 'user66',
      display_name: 'string',
      email: 'test.svietldf22ana1@gmail.com',
      avatar: null,
      phone: '+79261112233',
      date_joined: '2024-03-05T14:23:27.430000Z',
      country: 'string',
      city: 'string',
      first_name: 'string',
      last_name: 'string',
      bio: 'string',
      is_active: false,
      is_staff: false,
      is_admin: false,
    },
  },
  deleteUser: {
    username: 'test-user',
  },
}
